import { registerEnumType } from '@nestjs/graphql';

export enum UpdateActions {
  CHANGE_IN_PRICE = 'CHANGE_IN_PRICE',
  ADD_SALE_PRICE = 'ADD_SALE_PRICE',
  UPDATE_SALE_PRICE = 'UPDATE_SALE_PRICE',
  ADD_PROGRAM = 'ADD_PROGRAM',
  REMOVE_PROGRAM = 'REMOVE_PROGRAM',
  UPDATE_PROGRAM = 'UPDATE_PROGRAM',
  UPDATE_TITLE = 'UPDATE_TITLE',
  UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  UPDATE_THUMBNAIL = 'UPDATE_THUMBNAIL',
  UPDATE_PROMO_VIDEO = 'UPDATE_PROMO_VIDEO',
  UPDATE_INSTRUCTOR = 'UPDATE_INSTRUCTOR',
  ADD_INSTRUCTOR = 'ADD_INSTRUCTOR',
  REMOVE_INSTRUCTOR = 'REMOVE_INSTRUCTOR',
  UPDATE_INSTRUCTOR_COMMISION = 'UPDATE_INSTRUCTOR_COMMISION',
  CHANGE_VISIBALITY = 'CHANGE_VISIBALITY'
}
registerEnumType(UpdateActions, { name: 'UpdateActions' });
