import { registerEnumType } from '@nestjs/graphql';

export enum ContactReasonEnum {
  GENERAL_INQUIRY = 'GENERAL_INQUIRY',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  PAYMENT_AND_EARNINGS = 'PAYMENT_AND_EARNINGS',
  FEEDBACK_AND_SUGGESTIONS = 'FEEDBACK_AND_SUGGESTIONS',
  ACCOUNT_SUPPORT = 'ACCOUNT_SUPPORT',
  PROGRAM_ISSUES = 'PROGRAM_ISSUES',
  PAYOUT_QUESTIONS = 'PAYOUT_QUESTIONS',
  PARTNERSHIP_OPPORTUNITIES = 'PARTNERSHIP_OPPORTUNITIES',
  REPORT_A_PROBLEM = 'REPORT_A_PROBLEM',
  OTHER = 'OTHER',
  COURSE_AVAILABILITY_AND_DETAILS = 'COURSE_AVAILABILITY_AND_DETAILS',
  TEACHING_OPPORTUNITIES = 'TEACHING_OPPORTUNITIES',
  COLLABORATION_AND_PARTNERSHIP_INQUIRIES = 'COLLABORATION_AND_PARTNERSHIP_INQUIRIES',
  ACCOUNT_ASSISTANCE = 'ACCOUNT_ASSISTANCE',
  PAYMENT_AND_BILLING = 'PAYMENT_AND_BILLING',
  ENROLLMENT_AND_REGISTRATION_HELP = 'ENROLLMENT_AND_REGISTRATION_HELP',
  CERTIFICATION_AND_ACCREDITATION_INQUIRIES = 'CERTIFICATION_AND_ACCREDITATION_INQUIRIES',
  INSTRUCTOR_OPPORTUNITIES = 'INSTRUCTOR_OPPORTUNITIES',
  REPORT_ISSUE_OR_BUG = 'REPORT_ISSUE_OR_BUG',
  POST_REQUEST = 'POST_REQUEST',
  PERMISSION_ISSUE = 'PERMISSION_ISSUE',
  TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',

}

registerEnumType(ContactReasonEnum, {
  name: 'ContactReasonEnum'
});
