export enum CustomGraphqlErrorCodes {
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  QUERY_TOO_COMPLEX = 'QUERY_TOO_COMPLEX',
  RESOURCE_NOT_ALLOWED = 'RESOURCE_NOT_ALLOWED'
}
